"""Generate actionable synthetic normal/anomaly sample images.

The images are procedural brushed-metal-like textures (NOT real products):
- normal_*.png: intended for the reference and independent calibration sets;
- scratch_*.png and foreign_object_*.png: detection demos only and must never
  be used as reference or calibration data.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from PIL import Image

SIZE = 320


def _base_texture(seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    yy = np.arange(SIZE, dtype=np.float32)[:, None]
    xx = np.arange(SIZE, dtype=np.float32)[None, :]
    # Slow illumination gradient + deterministic brushed stripes + noise.
    gradient = 18.0 * (xx / SIZE) + 10.0 * (yy / SIZE)
    stripes = 9.0 * np.sin(yy * 0.55 + rng.uniform(0, 6.28))
    fine = 4.0 * np.sin(yy * 2.4 + rng.uniform(0, 6.28))
    noise = rng.normal(0, 3.0, size=(SIZE, SIZE))
    value = 168.0 + gradient * 0.25 + stripes + fine + noise
    value = np.clip(value, 0, 255)
    rgb = np.stack(
        [value - 6, value, value + 8], axis=-1
    )  # subtle cool metal tint
    return np.clip(rgb, 0, 255).astype(np.uint8)


def _add_scratch(texture: np.ndarray, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    out = texture.copy()
    x0, y0 = rng.integers(40, 120, size=2)
    x1, y1 = rng.integers(200, 290, size=2)
    width = rng.integers(2, 4)
    steps = 400
    for t in np.linspace(0, 1, steps):
        x = int(x0 + (x1 - x0) * t)
        y = int(y0 + (y1 - y0) * t + 4 * np.sin(t * 12))
        for dy in range(-width, width + 1):
            yy = y + dy
            if 0 <= yy < SIZE and 0 <= x < SIZE:
                out[yy, x] = np.clip(out[yy, x] * 0.35 + 20, 0, 255)
    return out


def _add_foreign_object(texture: np.ndarray, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    out = texture.copy().astype(np.float32)
    cy, cx = rng.integers(110, 210, size=2)
    radius = rng.integers(18, 28)
    yy, xx = np.mgrid[:SIZE, :SIZE]
    mask = ((yy - cy) ** 2 + (xx - cx) ** 2) <= radius ** 2
    color = np.array([40, 28, 20], dtype=np.float32)  # dark chip/dirt
    out[mask] = out[mask] * 0.25 + color
    # Highlight rim so the object reads as foreign rather than shading.
    rim = ((yy - cy) ** 2 + (xx - cx) ** 2 <= (radius + 2) ** 2) & ~mask
    out[rim] = np.clip(out[rim] + 35, 0, 255)
    return np.clip(out, 0, 255).astype(np.uint8)


def main() -> None:
    out_dir = Path(__file__).resolve().parents[1] / "examples"
    out_dir.mkdir(exist_ok=True)
    for i, seed in enumerate([101, 202, 303, 404, 505], start=1):
        Image.fromarray(_base_texture(seed)).save(out_dir / f"normal_{i}.png")
    normal = _base_texture(101)
    Image.fromarray(_add_scratch(normal, 9001)).save(out_dir / "scratch_1.png")
    Image.fromarray(_add_foreign_object(normal, 9002)).save(
        out_dir / "foreign_object_1.png"
    )
    readme = out_dir / "README.md"
    readme.write_text(
        "# Synthetic examples\n\n"
        "Procedural brushed-metal-like images generated by "
        "`scripts/generate_examples.py`; they are not photographs of real "
        "products.\n\n"
        "- `normal_1.png`..`normal_3.png`: normal samples. Upload to the "
        "reference and independent calibration sets.\n"
        "- `scratch_1.png`: a dark diagonal scratch; detection demo only.\n"
        "- `foreign_object_1.png`: an embedded dark particle/chip; detection "
        "demo only. Anomaly images must never be used for calibration.\n"
    )
    print(f"wrote examples to {out_dir}")


if __name__ == "__main__":
    main()
